[package]
name = "greenhouse-rs"
version = "0.1.0"
authors = ["QPCrummer"]
edition = "2021"
license = "MIT"

[[bin]]
name = "greenhouse-rs"
test = false
bench = false

[dependencies]
panic-halt = "1.0.0"
bme680 = "0.6.0"
heapless = { version = "0.8.0", features = ["ufmt"] }
lcd1602-driver = "0.2.0"
ufmt = "0.2.0"
ufmt_float = "0.2.0"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "3e362624547462928a219c40f9ea8e3a64f21e5f"
features = ["arduino-uno"]

# The latest releases of `proc-macro2` do not support the rust toolchain that
# we use.  Thus, we must fix this dependency to an older version where our
# toolchain is still supported.  See https://github.com/Rahix/avr-hal/issues/537
[build-dependencies.proc-macro2]
version = "=1.0.79"

# Configure the build for minimal size - AVRs have very little program memory
[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
